// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeApi.Data;

namespace PokeApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200514200940_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PokeApi.Model.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AvgSpawns")
                        .HasColumnType("double precision");

                    b.Property<string>("Candy")
                        .HasColumnType("text");

                    b.Property<int>("CandyCount")
                        .HasColumnType("integer");

                    b.Property<string>("Egg")
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int?>("PokemonId1")
                        .HasColumnType("integer");

                    b.Property<double>("SpawnChance")
                        .HasColumnType("double precision");

                    b.Property<string>("SpawnTime")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("PokemonId1");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeApi.Model.TypeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int?>("PokemonId1")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("PokemonId1");

                    b.ToTable("TypeElement");
                });

            modelBuilder.Entity("PokeApi.Model.Pokemon", b =>
                {
                    b.HasOne("PokeApi.Model.Pokemon", null)
                        .WithMany("NextEvolution")
                        .HasForeignKey("PokemonId");

                    b.HasOne("PokeApi.Model.Pokemon", null)
                        .WithMany("PrevEvolution")
                        .HasForeignKey("PokemonId1");
                });

            modelBuilder.Entity("PokeApi.Model.TypeElement", b =>
                {
                    b.HasOne("PokeApi.Model.Pokemon", null)
                        .WithMany("Type")
                        .HasForeignKey("PokemonId");

                    b.HasOne("PokeApi.Model.Pokemon", null)
                        .WithMany("Weaknesses")
                        .HasForeignKey("PokemonId1");
                });
#pragma warning restore 612, 618
        }
    }
}
