// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeApi.Data;

namespace PokeApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PokeApi.Model.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AvgSpawns")
                        .HasColumnType("double precision");

                    b.Property<string>("Candy")
                        .HasColumnType("text");

                    b.Property<int>("CandyCount")
                        .HasColumnType("integer");

                    b.Property<string>("Egg")
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<double>("SpawnChance")
                        .HasColumnType("double precision");

                    b.Property<string>("SpawnTime")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeApi.Model.PokemonNextEvolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("NextPokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NextPokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonNextEvolution");
                });

            modelBuilder.Entity("PokeApi.Model.PokemonPrevEvolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("PrevPokemonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("PrevPokemonId");

                    b.ToTable("PokemonPrevEvolution");
                });

            modelBuilder.Entity("PokeApi.Model.PokemonTypeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeElementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TypeElementId");

                    b.ToTable("PokemonTypeElement");
                });

            modelBuilder.Entity("PokeApi.Model.PokemonWeakness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeElementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TypeElementId");

                    b.ToTable("PokemonWeakness");
                });

            modelBuilder.Entity("PokeApi.Model.TypeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypeElement");
                });

            modelBuilder.Entity("PokeApi.Model.PokemonNextEvolution", b =>
                {
                    b.HasOne("PokeApi.Model.Pokemon", "NextPokemon")
                        .WithMany()
                        .HasForeignKey("NextPokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeApi.Model.Pokemon", "Pokemon")
                        .WithMany("NextEvolution")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeApi.Model.PokemonPrevEvolution", b =>
                {
                    b.HasOne("PokeApi.Model.Pokemon", "Pokemon")
                        .WithMany("PrevEvolution")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeApi.Model.Pokemon", "PrevPokemon")
                        .WithMany()
                        .HasForeignKey("PrevPokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeApi.Model.PokemonTypeElement", b =>
                {
                    b.HasOne("PokeApi.Model.Pokemon", "Pokemon")
                        .WithMany("Type")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeApi.Model.TypeElement", "TypeElement")
                        .WithMany()
                        .HasForeignKey("TypeElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeApi.Model.PokemonWeakness", b =>
                {
                    b.HasOne("PokeApi.Model.Pokemon", "Pokemon")
                        .WithMany("Weaknesses")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeApi.Model.TypeElement", "TypeElement")
                        .WithMany()
                        .HasForeignKey("TypeElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
